### ISSUE TITLE
Direct local .aar file dependencies are not supported when building an AAR.

### ISSUE THREAD

**Issue by dougbradbury** [melihyarikkaya/react-native-serialport#41]
I upgraded to react-native 0.64.2 (which included upgrading to gradle 6.7 and the android gradle plugin) and encountered this error

>  What went wrong:
> Execution failed for task ':react-native-serialport:bundleReleaseAar'.
> > Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-serialport project caused this error: .../node_modules/react-native-serialport/android/libs/usbserial-6.0.5-release.aar
> 

I've been trying to make the change according to [this article](https://stackoverflow.com/questions/60878599/error-building-android-library-direct-local-aar-file-dependencies-are-not-supp) but I am out of my depth on gradle.

**Comment by dougbradbury** [comment]
https://github.com/mikafi/react-native-serialport has solved the problem.

**Comment by jankoJelic** [comment]
I just ran into same issue as you can see here, when I run ./gradlew assembleRelease, after adding react-native-serialport to my project:

<img width="773" alt="Screenshot 2022-11-28 at 16 38 03" src="https://user-images.githubusercontent.com/78728156/204318684-dc08054e-4e70-49a9-8048-ebb5b1d85559.png">

How did you resolve it, @dougbradbury ?

"react-native-serialport": "^1.3.1"
"react-native": "0.65.1"

com.android.tools.build:gradle:4.2.1

**Comment by jankoJelic** [comment]
resolved this with app:assembleRelease instead of assembleRelease

**Comment by TetaBelyse** [comment]
> resolved this with app:assembleRelease instead of assembleRelease

@jankoJelic , I am using app:assembleRelease for building the app but am still facing the same issue. do you mind sharing how exactly you solved this issue? I've tried to find a solution online and most of them are suggesting adding some settings on build.gradle file and none of them is working.

error details:
Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-serialport project caused this error: C:\....\wimiti\node_modules\react-native-serialport\android\libs\usbserial-6.0.5-release.aar

**Comment by fabrice-niyongabo** [comment]
Did you guys manage to get a solution for this issue? still facing this issue. I am using "react-native-serialport": "^1.3.1"

**Comment by fabrice-niyongabo** [comment]
After a couple of days of trying to find a solution online, none of them worked. 
I have come up with a solution for this issue, just follow 4 simple steps:

1. Copy libs folder from yourProject/node_modules/react-native-serialport/android and then paste it into yourProject/android/app


2. From yourProject/node_modules/react-native-serialport/android/build.gradle

Under dependencies, change this line:
`implementation fileTree(dir: 'libs', include: ['usbserial-6.0.5-release.aar'])`
 to `compileOnly fileTree(dir: 'libs', include: ['usbserial-6.0.5-release.aar'])`

3. Make sure that you have made the necessary configurations for building a signed APK. [More details on the official site](https://reactnative.dev/docs/signed-apk-android#setting-up-gradle-variables)

4. Now build your project by: 
   cd android
   then run ./gradlew clean assembleRelease

Now, you should be able to build your project.

**Comment by flyskywhy** [comment]
[Fix `Direct local .aar file dependencies are not supported when building an AAR` when assemble release in gradle-6.7.1 or higher](https://github.com/flyskywhy/react-native-usb-serialport/commit/11d9b2f1c2ea882426f4d2b7d2c9d68e569911e3)
